### ISSUE TITLE
Unhealthy container upon repeated attempts to create proxy

### ISSUE THREAD

**Issue by corsairius** [cloud-py-api/docker-socket-proxy#23]
Numerous attempts to set up External Apps.  It keeps failing after Registration of the ExApp Docker Socket Proxy.

REPOSITORY                                  TAG       IMAGE ID       CREATED       SIZE
ghcr.io/cloud-py-api/test-deploy-cuda       release   de9e2833403e   10 days ago   8.3GB
ghcr.io/cloud-py-api/test-deploy-cpu        release   1e7a4086903a   10 days ago   1.33GB
ghcr.io/cloud-py-api/nextcloud-appapi-dsp   release   b18e1d6b9640   2 weeks ago   74.3MB
ghcr.io/nextcloud/llm2                      1.1.0     295cf9be1b09   6 weeks ago   14GB

CONTAINER ID   IMAGE                                               COMMAND                CREATED         STATUS                    PORTS     NAMES
b054776bce8b   ghcr.io/cloud-py-api/test-deploy-cpu:release        "python3 main.py"      8 minutes ago   Up 8 minutes (healthy)              nc_app_test-deploy
75cf509b3043   ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release   "/bin/bash start.sh"   17 hours ago    Up 17 hours (unhealthy)             nextcloud-appapi-dsp

Any ideas on how to correct an unhealthy container status?  

docker run -e NC_HAPROXY_PASSWORD="somePass" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --name docker_socket_proxy -h docker_socket_proxy \
  --restart unless-stopped --privileged -d ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release

[Nextcloud Hub 7](https://nextcloud.com/) (28.0.5) ----------------------------

Computer: ----------------------------
Operating System: Linux 5.15.0-105-generic x86_64
CPU: Intel(R) Xeon(R) CPU E5649 @ 2.53GHz (24 cores)
Memory: 125.78 GB
Server time: Tue May 7 10:10:20 CDT 2024

Docker ----------------------------
docker0
Status: up

Database ----------------------------
Type: pgsql
Version: PostgreSQL 16.2 (Ubuntu 16.2-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit
Size: 2.1 GB

PHP ----------------------------
Version: 8.1.28
Memory limit: 10 GB
Max execution time: 10000
Upload max size: 20 GB
OPcache Revalidate Frequency: 60
Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, bz2, intl, pdlib, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

I was hopeful that it was a healthy container issue in this error message:

`cURL error 6: Could not resolve host: nextcloud-appapi-dsp (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://nextcloud-appapi-dsp:2375/v1.41/_ping`

My Nextcloud instance is solely https, however. So perhaps opening http back up may help?

Thanks!

**Comment by bigcat88** [comment]
I will try to find time next week to fix `unhealthy` status for DockerSocketProxy container.

_But it should not affect installing External Apps, there is just a slightly wrong logic in "healthcheck.sh"_

**Comment by corsairius** [comment]
I was hopeful that it was a healthy container issue in this error message:

`cURL error 6: Could not resolve host: nextcloud-appapi-dsp (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://nextcloud-appapi-dsp:2375/v1.41/_ping`

My Nextcloud instance is solely https, however.  So perhaps opening http back up may help?

**Comment by corsairius** [comment]
I had to remove 2.6.0 of App_api using the occ app:disable command.  Lost my GUI after update.

**Comment by andrey18106** [comment]
@corsairius ExAppScopesService was removed in this version, could you verify if it works after webserver restart, maybe it was cached in PHP.

**Comment by corsairius** [comment]
OK.  Restarted nginx, but then had to restart php8.1-fpm.

**Comment by corsairius** [comment]
Whatever I was doing wrong, likely using localhost:2375, it is taking a long time to initialize.

**Comment by andrey18106** [comment]
Does AppAPI 2.6.0 working without errors in the logs after php-fpm and nginx restart? Does the Deploy daemon in AppAPI admin settings verifies connection?

**Comment by corsairius** [comment]
Overall, no.  Yes, AppAPI works without the above error after php-fpm and nginx restart.  No, deleting the configuration and restarting verification fails.  I will have to get to this later, and recheck my settings.

**Comment by corsairius** [comment]
Nope.  Isn't working with the simplest install.  Must be missing something.  Just close this issue; I'll revisit in a few months.

**Comment by corsairius** [comment]
I need to verify the process of creating the deploy daemon, and simply register the default deploy daemon.

- Install Nextcloud Assistant
- Install AppAPI
- Go to Administration Settings off of the user icon
- Go to AppAPI in left panel
- Click Register, and enter the configuration as identified here [CreationOfDeployDaemon](https://cloud-py-api.github.io/app_api/CreationOfDeployDaemon.html#create-deploy-daemon) although here [cloud-py-api](https://github.com/cloud-py-api/docker-socket-proxy) indicates that it is my admin task to create the docker container.
- Does the UI download and create the docker container? "We highly recommend to use UI to create Deploy Daemons."
- Does creating Deploy Daemons include the docker-deploy selection, orchestrating the docker container creation?

I've been creating the docker container and I have not been creating the container. With creating the docker container, the container fails to initialize.  With just using the UI, is returns Test deploy Start within seconds.  It is unclear what is essential and what is not.  The binding of ports isn't an option within the UI, so I went the direction of creating the container.  That resulted in the Initialization failure, repeatedly.  Updating php from 8.1 to 8.2 and moving from 28.x to 29.0.1 did not result in success. 

I'm unsure as to what is really required for the setup of a docker api socket instance on the same device as the nextcloud installation.  Nextcloud isn't running in a VM.  The only way I get to initialization is to reboot while in the Test Deploy phase with the Docker container already running.  Thinking I just need http access, I re-enabled the http local host side for internal use.  I do not forward the http port. <shrug>

**Comment by bigcat88** [comment]
"Unhealthy" status of docker container now should gone with `1.3.0` version

Related to your last message of how to make "TestDeploy" succeed or problem in installing applications - fell free to create an issue in AppAPI repo if it is not related to docker socket proxy and we will try from scratch to solve the issue.
